/*
 * File Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Text;
using System.Runtime.Serialization;

namespace Rkk2._0.Controllers.Ei
{

    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class FileInboxMultipartStartKindPostRequest : IEquatable<FileInboxMultipartStartKindPostRequest>
    {
        /// <summary>
        /// Gets or Sets FileName
        /// </summary>
        [DataMember(Name="fileName", EmitDefaultValue=false)]
        public string FileName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FileInboxMultipartStartKindPostRequest {\n");
            sb.Append("  FileName: ").Append(FileName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((FileInboxMultipartStartKindPostRequest)obj);
        }

        /// <summary>
        /// Returns true if FileInboxMultipartStartKindPostRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of FileInboxMultipartStartKindPostRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FileInboxMultipartStartKindPostRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    FileName == other.FileName ||
                    FileName != null &&
                    FileName.Equals(other.FileName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (FileName != null)
                    hashCode = hashCode * 59 + FileName.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(FileInboxMultipartStartKindPostRequest left, FileInboxMultipartStartKindPostRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(FileInboxMultipartStartKindPostRequest left, FileInboxMultipartStartKindPostRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
