/*
 * File Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Text;
using System.Runtime.Serialization;

namespace Rkk2._0.Controllers.Ei
{

    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class MultipartUploadStartResult : IEquatable<MultipartUploadStartResult>
    {
        /// <summary>
        /// Gets or Sets UploadId
        /// </summary>
        [DataMember(Name="uploadId", EmitDefaultValue=true)]
        public long UploadId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MultipartUploadStartResult {\n");
            sb.Append("  UploadId: ").Append(UploadId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }



        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((MultipartUploadStartResult)obj);
        }

        /// <summary>
        /// Returns true if MultipartUploadStartResult instances are equal
        /// </summary>
        /// <param name="other">Instance of MultipartUploadStartResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MultipartUploadStartResult other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    UploadId == other.UploadId ||
                    
                    UploadId.Equals(other.UploadId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + UploadId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(MultipartUploadStartResult left, MultipartUploadStartResult right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(MultipartUploadStartResult left, MultipartUploadStartResult right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
